# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

IP_NW = "192.168.56."

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"
  config.vm.box = "ubuntu/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Provision Master Nodes
#  (1..NUM_MASTER_NODE).each do |i|
#      config.vm.define "master-#{i}" do |node|
#        # Name shown in the GUI
#        node.vm.provider "virtualbox" do |vb|
#            vb.name = "kubernetes-ha-master-#{i}"
#            vb.memory = 2048
#            vb.cpus = 2
#        end
#        node.vm.hostname = "master-#{i}"
#        node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
#        node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
#
#
#      end
#  end

  # Provision Load Balancer Node
  config.vm.define "target" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "target"
        vb.memory = 512
        vb.cpus = 1
    end
    node.vm.hostname = "target"
    node.vm.network :private_network, ip: IP_NW + "10"
    node.vm.network "forwarded_port", guest: 22, host: 2730

    node.vm.provision "file", source: "scripts/RemoteRat.sh", destination: "$HOME/RemoteRat.sh"
    node.vm.provision "shell", inline: "chmod +x /home/vagrant/RemoteRat.sh"
  end

  # Provision Load Balancer Node
  config.vm.define "attacker" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "attacker"
        vb.memory = 512
        vb.cpus = 1
    end
    node.vm.hostname = "attacker"
    node.vm.network :private_network, ip: IP_NW + "20"
    node.vm.network "forwarded_port", guest: 22, host: 2740

    node.vm.provision "file", source: "scripts/LocalRat.sh", destination: "$HOME/LocalRat.sh"
    node.vm.provision "shell", inline: "chmod +x /home/vagrant/LocalRat.sh"
  end

  config.vm.provision "setup-hosts", :type => "shell", :path => "scripts/setup-hosts.sh" do |s|
    s.args = ["enp0s8"]
  end

end
